### ISSUE TITLE
Why is the vertical axis flipped sometimes?

### ISSUE THREAD

**Issue by philipbaileynar** [cheginit/py3dep#1] opened 2021-03-01 18:44 UTC
We are calling py3DEP with geoJSON polygon boundaries and sometimes the data are returned with the vertical axis flipped. Here is an example:

https://github.com/Riverscapes/riverscapes-tools/blob/3dep/packages/rscontext/research/3dep_testing.ipynb

This only happens sometimes and we can't figure out the pattern as to why. Any advice would be appreciated!

**Comment by cheginit** [comment] 2021-03-01 20:05
Thanks for providing the example notebook.

The issue seems to be with `matplotlib`, since when I plot them with `xarray` itself, it looks fine:
![image](https://user-images.githubusercontent.com/13016644/109551824-a6612700-7a96-11eb-9d98-c78b5b7d7526.png)

![image](https://user-images.githubusercontent.com/13016644/109551870-b7aa3380-7a96-11eb-9303-bc045ed3180b.png)

**Comment by KellyMWhitehead** [comment] 2021-03-01 21:23
Thank you for the quick response!

I still seem to be having reversed y values when I save the array to geotiff.

I will admit I have not used xarrays much, but when I look at the y coordinates they do appear to be in reversed order between the 10m and 1.1m dems:
![image](https://user-images.githubusercontent.com/10746997/109560384-ab22dc80-7a90-11eb-88bb-4f5017b8860b.png)

**Comment by cheginit** [comment] 2021-03-01 22:56
Ah, I see what you mean. This is a known issue with `xarray.merge`, you can check it [here](https://github.com/pydata/xarray/pull/2972).
Py3DEP, under-the-hood, decomposes large requests into smaller chunks then merge the results before returning it to the user. The 10-km resolution doesn't need any decomposition so the data is returned without any need for merging but 1-km resolution has to be decomposed and then merged which leads to this issue.
A quick fix for this case is to sort the 1-km dataset to match that of the 10-km dataset:
![image](https://user-images.githubusercontent.com/13016644/109569825-abca6b80-7aae-11eb-841c-f9ccd6058d9c.png)

**Comment by cheginit** [comment] 2021-03-01 23:00
Since the PR on `xarray` is still open, I will push a temporary fix for Py3DEP until the PR in `xarray` gets merged.

**Comment by cheginit** [comment] 2021-03-01 23:27
@philipbaileynar and @KellyMWhitehead, thanks for opening the issue. I pushed a fix, you can either update Py3DEP using `pip install  --no-deps -U git+https://github.com/cheginit/py3dep` to get the fix or use the sort method that I mentioned earlier until I officially release a new version (probably by the end of the next week).

**Comment by cheginit** [comment] 2021-03-02 00:37
I addressed issue in the upstream package, [PyGeoUtils](https://github.com/cheginit/pygeoutils), so you can install the fix by updating that package instead, i.e. `pip install --no-deps -U git+https://github.com/cheginit/pygeoutils` or, as I said, just sort it manually and wait for the upcoming official release.

**Comment by cheginit** [comment] 2021-04-15 17:58
Since the issue is resolved, I will close it. Please feel free to reopen if you still have the issue.

**Closed** 2021-04-15 18:11 UTC
