### ISSUE TITLE
Returned transform is incorrect

### ISSUE THREAD

**Issue by theobarnhart-USGS** [cheginit/py3dep#3] opened 2021-03-19 20:54 UTC
Really cool collection of libraries you have here. Thank you for making these data more readily accessible in Python!

**What happened**:
I pulled a hillshade using py3dep.get_map using a bounding box computed from a shapefile using geopandas. When I plotted the map using rs.plot.show() using the included transform and then plotted a shapefile on top (same CRS) the shapefile and the map do not align, the hillshade was shifted ~2 degrees south of the shapefile. Comparing the bounding box and the transform, which I think provides the coordinates for the upper left corner, the latitude of the upper left is ~48.75, but should be ~50.63 based on the bounding box provided. When I make a new transform tuple, using the correct latitude, the shapefile and map align.

**What you expected to happen**:

I expected the map and the shapefile to align.

**Minimal Complete Verifiable Example**:

```python
bbox = (-124.90220439999996,
 41.12782617100004,
 -109.76249144199994,
 50.634716809000054)

bm = py3dep.get_map(layers='Hillshade Gray', geometry=bbox,geo_crs='epsg:4326', crs='epsg:4326', resolution=300)

print(bm.transform)
print(bbox)
```

Original shapefile and map with returned transform:
![image](https://user-images.githubusercontent.com/30270490/111841045-f1ff3780-88c2-11eb-84ca-265f3e3516c6.png)

Aligned shapefile and map, after updating transform:
![image](https://user-images.githubusercontent.com/30270490/111840981-db58e080-88c2-11eb-9496-fad15d4f1e77.png)

**Anything else we need to know?**:

**Environment**:
conda-forge
<details><summary>Output of <tt>INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 | packaged by conda-forge | (default, Jul 24 2020, 01:25:15) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.4.0-17763-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

pygeohydro: None
pygeoogc: 0.10.0
pygeoutils: 0.10.0
py3dep: 0.10.0
pynhd: None
pydaymet: None
xarray: 0.16.1
rasterio: 1.1.5
geopandas: 0.8.1
pandas: 1.1.0
orjson: 3.5.1
shapely: 1.7.0
scipy: 1.5.2
netCDF4: 1.5.4
defusedxml: 0.6.0
owslib: 0.23.0
pyproj: 2.6.1.post1
requests: 2.25.1
pygeos: None
matplotlib: 3.3.0
bottleneck: None
dask: 2.30.0
cartopy: 0.17.0
setuptools: 49.2.0.post20200712
pip: 20.2
conda: None
mamba: None
pytest: 6.2.2
IPython: 7.16.1
sphinx: None</tt></summary>

</details>

**Comment by cheginit** [comment] 2021-03-19 21:38
Thanks for the detailed bug report. The issue seems to be with the merging step. I just pushed a fix to `pygeoutils`. Please update the package from its git repo using `pip install --no-deps git+https://github.com/cheginit/pygeoutils.git` and check if it solves the issue.

**Comment by theobarnhart-USGS** [comment] 2021-03-19 22:05
That's definitely better, but now the transform attribute in the DataArray comes across as an Affine transformation (I think this is better, actually) and I have to use bm.values to get it to plot. Otherwise, I get this error: 
![image](https://user-images.githubusercontent.com/30270490/111846642-ddc03800-88cc-11eb-8571-bcc8a650f36b.png)

Has something changed in the creation of that DataArray?

Aside from that, my vector appears to be in the right place! Thank you!

**Comment by cheginit** [comment] 2021-03-19 22:15
Yes, transform is an Affine object now. Glad the issue is resolved. Please let me know if there's any other issues.

**Closed** 2021-03-19 22:22 UTC
